# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "15cba03ec88bed183a2e8630814c8cb7"
name = "Page Builder App"
application_url = "https://example.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_content,write_content,write_files"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]
